/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:c2679bf9-471d-4359-be5e-bf5d182a17ca",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_zORYRICdV",
    "aws_user_pools_web_client_id": "vpsrchdf7cj8j7er1n3fkeqmv",
    "oauth": {
        "domain": "vcrptob0f427ee-b0f427ee-dev.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000/",
        "redirectSignOut": "exp://127.0.0.1:19000/",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_appsync_graphqlEndpoint": "https://rjjtfsbtxjfgffurclnltoyexa.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
